config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :staffs, controllers: {
        registrations: 'staff/registrations'
      }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'page#index'

  get "/api/houses" => 'api#houses'
  get "/api/houses/activities" => 'api#house_points_by_activity'
  get "/api/staff" => 'api#staff'
  get "/api/staff/:id" => 'api#specific_staff'
  get "/api/staff/activities" => 'api#staff_assignment_by_activity'
  get "/api/members" => 'api#members'
  get "/api/members/top" => 'api#top_members'
  get "/api/members/bottom" => 'api#bottom_members'
  get "/api/members/:id" => 'api#member'
  get "/api/houses" => 'api#houses'
  get "/api/top_points" => 'api#top_points'
  post "/api/behavior_report" => "api#member_behavior_report"
  post '/api/ssm' => 'api#ssm_add'

  get "/students" => 'page#students'

  get ':school' => 'page#show'
  get ':school/stylesheet' => 'page#stylesheet'
  get ':school/about' => 'page#about'

  get ':school/score' => 'page#add'
  post ':school/score' => 'page#doadd'

  get ':school/house/:id' => 'page#invite'
  post ':school/house/:id' => 'page#doinvite'

  get ':school/invite' => 'page#create_invite'
  post ':school/invite' => 'page#do_create_invite'

end

app/views/admin/dashboard/_charts.html.erb
<% houses = House.where(:school_id => current_admin_user.school_id.to_s).all %>
<% staff = Staff.where(:school_id => current_admin_user.school_id.to_s).all %>
<div style="min-width: 100%; float: left">
	<center><h2>Activities In Each House</h2></center>
	<% houses.each do |h| %>
		<div style="width: 50%; float: left">
			<center><b><%= h.name %></b></center>
			<div id="housePoints-<%= h.id %>" style="width:100%;height:300px"></div>
		</div>
	<% end %>
</div>
<div style="min-width: 100%; float: left">
	<center><h2>Activities Reported By Staff</h2></center>
	<% staff.each do |s| %>
		<div style="width: 50%; float: left">
			<center><b><%= s.email %></b></center>
			<div id="staffactivity-<%= s.id %>" style="width:100%;height:300px"></div>
		</div>
	<% end %>
</div>

<div style="min-width: 100%; float: left">
	<center><h2>Who Gives Out The Most Points?</h2></center>
		<div>
			<div id="mostpoints" style="width:100%;height:300px"></div>
		</div>
</div>
<script type="text/javascript" src="/js/flot/jquery.flot.min.js"></script>
<script type="text/javascript" src="/js/flot/jquery.flot.pie.min.js"></script>
<script>
	var houses, activities, staff;
	$(document).ready(function(){
		$.get("/api/houses")
		.success(function(data){
			houses = data;
			$.get("/api/staff")
			.success(function(data){
				staff = data;
				$(window).trigger('resize');
			});
		});

		window.onresize = function(event) {
			for (var i = 0; i < houses.length; i++)
			{
				$.get("/api/houses/activities?house_id="+houses[i].id)
				.success(function(data){
					$.plot("#housePoints-" + data.house, data.data, 
						{
							series: {
								pie: {
									show: true
								}
							},
							legend: {
								show: true,
								offet: {
									left: 0
								},
								position: "ne"
							}
						}
					);
				});
			}

			for (var i = 0; i < staff.length; i++ )
			{

				$.get("/api/staff/activities?staff_id="+staff[i].id)
				.success(function(data){
					$.plot("#staffactivity-"+data.staff,data.data, 
						{
							series: {
								pie: {
									show: true
								}
							},
							legend: {
								show: true,
								offet: {
									left: 0
								},
								position: "ne"
							}
						}
					);
				});
			}	
		
			$.get("/api/top_points")
			.success(function(data){
				$.plot("#mostpoints",data , 
					{
						series: {
							pie: {
								show: true
							}
						},
						legend: {
							show: true,
							offet: {
								left: 0
							},
							position: "ne"
						}
					}
				);
			});
		};
	});
</script>

app/views/admin/dashboard/_dashboard.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="btn-group" role="group" aria-label="...">
		  <a href="#staff" type="button" class="btn btn-default" data-bind="style: { 'background-color': selectedView() == 'staff' ? 'grey' : 'white' }">Staff</a>
		  <a href="#members" type="button" class="btn btn-default" data-bind="style: { 'background-color': selectedView() == 'members' ? 'grey' : 'white' }">Students</a>
		  <a href="#houses" type="button" class="btn btn-default" data-bind="style: { 'background-color': selectedView() == 'houses' ? 'grey' : 'white' }">Houses</a>
		  <!-- <a href="#settings" type="button" class="btn btn-default" data-bind="style: { 'background-color': selectedView() == 'settings' ? 'grey' : 'white' }">Settings</a> -->
		</div>
	</div>
</div>
<br/>
<br/>
<div class="row">
	<div class="col-md-3">
		<div id="staffList" data-bind="visible: selectedView() == 'staff'">
			<ul data-bind="foreach: staff" class="list-group">
				<li class="list-group-item">
					<a href="#" data-bind="text: email, attr: { href: '#staff/'+ id } "></a>
				</li>
			</ul>
		</div>
		<div id="membersList" data-bind="visible: selectedView() == 'members'">
			<ul data-bind="foreach: members" class="list-group">
				<li class="list-group-item">
					<a href="#" data-bind="text: name + ' ('+ badge_id + ')', attr: { href: '#members/'+ id } "></a>
				</li>
			</ul>
		</div>
		<div id="housesList" data-bind="visible: selectedView() == 'houses'">
			<ul data-bind="foreach: houses" class="list-group">
				<li class="list-group-item">
					<a href="#" data-bind="text: name, attr: { href: '#houses/'+ id } "></a>
				</li>
			</ul>
		</div>
	</div>
	<div class="col-md-9">
		<div id="staffOverview" data-bind="visible: selectedSubView() == 'allStaff'">
			This Page Coming Soon!
		</div>
		<div id="staffDetails" data-bind="with: selectedStaff, visible: selectedSubView() == 'specificStaff'">
			Name: <span data-bind="text: name"></span><br/>
			Email: <span data-bind="text: email"></span><br/>
			House: <span data-bind="text: house"></span><br/>
			Grade: <span data-bind="text: grade"></span><br/>
		</div>
		<div id="membersOverview" data-bind="visible: selectedSubView() == 'allMembers'">
			<div class="col-md-6">
				<h3>Top Students</h3>
				<div data-bind="foreach: topMembers">
					<h4 data-bind="text: name"></h4>
					<ul data-bind="foreach: members">
						<li>
							<a href="#" data-bind="text: name + ' (' + badge_id+ ') - ' + points + ' points', attr: {href: '#members/'+id}"></a>
						</li>
					</ul>
				</div>
			</div>

			<div class="col-md-6">
				<h3>Bottom Students</h3>
				<div data-bind="foreach: bottomMembers">
					<h4 data-bind="text: name"></h4>
					<ul data-bind="foreach: members">
						<li>
							<a href="#" data-bind="text: name + ' (' + badge_id+ ') - ' + points + ' points', attr: {href: '#members/'+id}"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div id="housesOverview" data-bind="visible: selectedSubView() == 'allHouses'">
			<h3>Current Score</h3>
			<ul class="col-xs-12" data-bind="foreach: houses">
				<li style="font-size: 20px;" data-bind="text: name + ': ' + points + ' points'">
				</li>
			</ul>
		</div>
		<div id="settingsOverview" data-bind="visible: selectedView() == 'settings'">
			Coming Soon!
		</div>
	</div>
</div>

<%= javascript_include_tag "dashboard" %>