config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :staffs, controllers: {
        registrations: 'staff/registrations'
      }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'page#index'

  get "/api/houses" => 'api#houses'
  get "/api/houses/activities" => 'api#house_points_by_activity'
  get "/api/staff" => 'api#staff'
  get "/api/staff/:id" => 'api#specific_staff'
  get "/api/staff/activities" => 'api#staff_assignment_by_activity'
  get "/api/members" => 'api#members'
  get "/api/members/top" => 'api#top_members'
  get "/api/members/bottom" => 'api#bottom_members'
  get "/api/members/:id" => 'api#member'
  get "/api/houses" => 'api#houses'
  get "/api/top_points" => 'api#top_points'
  post "/api/behavior_report" => "api#member_behavior_report"
  post '/api/ssm' => 'api#ssm_add'

  get "/students" => 'page#students'

  get ':school' => 'page#show'
  get ':school/stylesheet' => 'page#stylesheet'
  get ':school/about' => 'page#about'

  get ':school/score' => 'page#add'
  post ':school/score' => 'page#doadd'

  get ':school/house/:id' => 'page#invite'
  post ':school/house/:id' => 'page#doinvite'

  get ':school/invite' => 'page#create_invite'
  post ':school/invite' => 'page#do_create_invite'

end

app/views/page/about.html.erb
<div class="row">
	<div class="col-xs-12">
		<%= @school.about.html_safe %>
	</div>
</div>

app/views/page/add.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
	  <div class="form-group">
      <% if @super_simple_mode %>
      <div class="row">
        <div class="col-xs-12" style='padding-bottom: 15px'>
            How Many Times?
            <input type="number" class='form-control' id='ssm_times' value='1' />
        </div>
      </div>
      <div class="row">
        <div class='col-xs-12'>
            
        </div>
      </div>
      <% end %>
    <div class="row">
        <% @houses.each do |h| %>
    	<div class="col-xs-<%= @col_size_xs %> col-md-<%= @col_size_md %> col-sm-<%= @col_size_sm %>">
            <% if @super_simple_mode %>
                <center>
                    <img src="<%= h.image.url %>" class="img-responsive ssm" id="ssm-<%= h.id %>" data-name='<%= h.name %>' />
                    <% if @showHouseTextNames %>
                        <br/>
                        <h3><%= h.name %></h3>
                    <% end %>
                </center>
            <% else %>
        		<a href="#" class="item">
        			<center>
                        <img src="<%= h.image.url %>" class="img-responsive" id="<%= h.id %>" />
                        <% if @showHouseTextNames %>
                            <br/>
                            <h3><%= h.name %></h3>
                        <% end %>
                    </center>
        		</a>
            <% end %>
    	</div>
        <% end %>
    </div>
  </div>
  <% if !@super_simple_mode %>
  <div class="form-group">
    <% if @custom_points %>
        <div>
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#list" aria-controls="list" role="tab" data-toggle="tab">List</a></li>
            <li role="presentation"><a href="#custom" aria-controls="custom" role="tab" data-toggle="tab">Custom</a></li>
          </ul>
          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="list">
                <label for="exampleInputPassword1">Activity</label>
                <select class="form-control" id="activity">
                    <option value="">- Select One -</option>
                    <% @activities.each do |a| %>
                    <option value="<%= a.id %>"><%= a.name %></option>
                    <% end %>
                </select>
                <% if @track_student == true %>
                    <div id="studentWrapperList">
                        <label for="student">Student</label>
                        <input type="text" class="form-control typeahead" id="studentText"/>
                        <div id="studentListSet"></div>
                    </div>
                <% end %>
                <% if @show_note == true %>
                    <label for="note">Note</label>
                    <textarea class="form-control" id="note_list"></textarea>
                <% end %>
                <% if @can_add_multiple %>
                    <label for="times">Add Points This Many Times</label>
                    <input type="number" class="form-control" id="times_list"/>
                <% end %>
            </div>
            <div role="tabpanel" class="tab-pane" id="custom">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title"/>
                <label for="amount">Points</label>
                <input type="number" class="form-control" id="amount"/>
                <% if @track_student == true %>
                    <div id="studentWrapperCustom">
                        <label for="student">Student</label>
                        <input type="text" class="form-control typeahead" id="studentTextCustom"/>
                        <div id="studentListCustom"></div>
                    </div>
                <% end %>
                <% if @show_note == true %>
                    <label for="note">Note</label>
                    <textarea class="form-control" id="note_custom"></textarea>
                <% end %>
                <% if @can_add_multiple %>
            <label for="times">Add Points This Many Times</label>
            <input type="number" class="form-control" id="times_custom"/>
        <% end %>
            </div>
          </div>

        </div>
    <% else %>
        <label for="exampleInputPassword1">Activity</label>
        <select class="form-control" id="activity">
            <option value="">- Select One -</option>
            <% @activities.each do |a| %>
        	<option value="<%= a.id %>"><%= a.name %></option>
            <% end %>
        </select>
        <% if @track_student == true %>
            <label for="gradeList">Student Grade</label>
            <select id="gradeList" class="form-control">
            <option value="">- Select One -</option>
            <% @grades.each do |g| %>
                <option value="<%= g %>"><%= g %></option>
            <% end %>
            </select>
            <div style="display: none" id="studentWrapperList">
                <label for="student">Student</label>
                <input type="text" class="form-control typeahead" id="studentList"/>
                <input type="hidden" id="member_id_list" />
            </div>
        <% end %>
        <% if @show_note == true %>
            <label for="note">Note</label>
            <textarea class="form-control" id="note_list"></textarea>
        <% end %>
        <% if @can_add_multiple %>
            <label for="times">Add Points This Many Times</label>
            <input type="number" class="form-control" id="times_list"/>
        <% end %>
    <% end %>
  </div>
  <button type="submit" class="btn btn-default form-control" id="submit">Submit</button>
</div>
    <% end %>
</div>
<%= javascript_include_tag params[:controller] %>
<% if @super_simple_mode %>
    <script type="text/javascript">
        var staff_id = <%= current_staff.id %>;
        var points = <%= @ssm_points %>;
    </script>
<% end %>

app/views/page/create_invite.html.erb
<div class="row">
	<%= form_tag do %>
		<h2>How many QR Codes should we generate?</h2>
		<input type="text" class="form-control" name="amount" id="amount" />
		</br>
		<button type="submit" class="form-control btn btn-primary">Generate</button>
	<% end %>
</div>

app/views/page/do_create_invite.html.erb
<div class="row">
	<% i = 0
	@codes.each do |code|  %>
		<div class="col-xs-6" style="page-break-inside: avoid">
			<center><h2><%= @school.name %></h2>
			<img src="<%= code.resize(200,200).to_data_url %>" class="img-responsive"/>
			<h2>House Cup</h2></center>
		</div>
	<% end %>
</div>

app/views/page/index.html.erb
<div class="row">
	<h3><center>Welcome to the Gradery House Cup system. Select your school from the list below</center></h3>
</div>
<div class="row">
	<% @schools.each do |s| %>
		<div class="col-xs-12">
			<center><h4><a href="/<%= s.url %>"><%= s.name %></a></h4></center>
		</div>
	<% end %>
</div>

app/views/page/invite.html.erb
<div class="row">
	<div class="col-xs-12">
		<center>
			<h1>Welcome to</h1>
		</center>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<center>
			<img src="<%= @house.image.url %>" class="img-responsive" />
		</center>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<center>
			<h2><%= @house.name %> House!</h2>
		</center>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<center>
			<h3>Enter Student ID</h3>
			<input type="text" id="studentId" class="form-control"/></br>
			<h3>Enter Student Name</h3>
			<input type="text" id="name" class="form-control"/></br>
			<button class="btn btn-primary form-control" id="invite">Add To House</button>
		</center>
	</div>
</div>

app/views/page/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<center>
			<h2><%= @school.name %> <%= @house_term %> Cup Standings</h2>
			<br/><br/><br/>
		</center>
	</div>
</div>
<div class="row">
<% i = 1
@houses.each do |h| %>
	<div class="col-xs-<%= 12/ @houses.count%> <%= 'col-xs-offset-1' if @houses.count == 5 && i == 1 %>">
		<center>
			<img src="<%= h.image.url %>" class="img-responsive"/>
			<% if @showHouseTextNames %>
				<br/>
				<h3><%= h.name %></h3>
			<% end %>
		</center>
	</div>
	<% i = i + 1 %>
<% end %>
</div>
<div class="row">
<% i = 1
@houses.each do |h| %>
	<div class="col-xs-<%= 12/ @houses.count%> <%= 'col-xs-offset-1' if @houses.count == 5 && i == 1 %>">
		<center>
			<div id="score-<%= i %>" class="score">
		    <div class="outer" style="height: 150px">
		        <div class="inner" data-progress="<%= (h.points.to_f / @max_score.to_f) * 100 %>%" style="background-color: <%= h.color %>">
		        </div>        
		    </div>
			</div>
			<% if !@housePointsAsMoney %>
				<b class="score"><%= number_with_delimiter(h.points)%> Points</b>
			<% else %>
				<b class="score"><%= number_to_currency(h.points, precision: 0)%></b>
			<% end %>
		</center>
	</div>
	<% i = i + 1 %>
<% end %>
</div>
<%= javascript_include_tag params[:controller] %>
<script type="text/javascript">
	setTimeout(function(){
		location.reload();
	}, 60 * 60 * 1000);
</script>

app/views/page/stylesheet.erb
.navbar{
	background-color: <%= @navbarBackgroundColor %>;
	color: <%= @foregroundColor %>;
}

.navbar-default a{
	color: <%= @foregroundColor %> !important;
}

.navbar-toggle, .navbar-toggle:hover, .navbar-toggle:active{
	background-color: <%= @buttonColor %> !important;
}

.btn{
	background-color: <%= @buttonColor %>;
	color: <%= @foregroundColor %>;
}

body{
	background-color: <%= @backgroundColor %>;
	color: <%= @textColor %>;
}

a{
    color: <%= @textColor %>;
}

.nav-pills > li.active > a, .nav-pills > li.active > a:hover, .nav-pills > li.active > a:focus{
	background-color: <%= @buttonColor %> !important;
	color: <%= @foregroundColor %> !important;
}

.pagination > .active > a{
	background-color: <%= @buttonColor %> !important;
	color: <%= @foregroundColor %> !important;
}